<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Zeyneps-MBP" failures="1" tests="6" name="tests.SignUpPageTest" time="101.260" errors="0" timestamp="2021-04-04T15:10:07 EDT" skipped="1">
  <testcase classname="tests.SignUpPageTest" name="registerWithValidCredential" time="23.646"/>
  <system-out/>
  <testcase classname="tests.SignUpPageTest" name="signUpWithFaceBookTest" time="13.779">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.SignUpPageTest.signUpWithFaceBookTest(SignUpPageTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- signUpWithFaceBookTest -->
  <system-out>
<a href='/Users/zeynepunalan/eclipse-workspace/ISpeakBetter_Group2/target/surefire-reports/failure_screenshots/signUpWithFaceBookTest_04_04_2021_03_04_58.png'> <img src='/Users/zeynepunalan/eclipse-workspace/ISpeakBetter_Group2/target/surefire-reports/failure_screenshots/signUpWithFaceBookTest_04_04_2021_03_04_58.png' height='100' width='100'/> </a>  </system-out>
  <testcase classname="tests.SignUpPageTest" name="registerWithExistingEmailAddressTest" time="15.594"/>
  <system-out/>
  <testcase classname="tests.SignUpPageTest" name="registerWithMandotoryFieldTest" time="22.848"/>
  <system-out/>
  <testcase classname="tests.SignUpPageTest" name="registerWithoutAlphanumericPwdTest" time="25.393"/>
  <system-out/>
  <testcase classname="tests.SignUpPageTest" name="registerWithInvalidEmailTest">
    <skipped/>
  </testcase> <!-- registerWithInvalidEmailTest -->
  <system-out/>
</testsuite> <!-- tests.SignUpPageTest -->
